language: android
jdk: oraclejdk8
sudo: require

android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.2
    - android-24
    - sys-img-armeabi-v7a-android-22
    - extra-android-m2repository
    - compile 'com.google.android.gms:play-services:9.6.1'
    - compile 'com.android.support:support-annotations:24.2.1'
    - compile 'com.google.firebase:firebase-core:9.4.0'
    - compile 'com.google.android.gms:play-services-auth:9.6.1'

  licenses: 		      
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'		      	     

script: ./gradlew 

